harmonica_size = 22
harmonica_position = 82
tabs_size = 16
tabs_position = 86
shade_opacity = 56
shade_top = 73
shade_bottom = 0
rotate = 0
tabs_font = 0
harm_font = 45
chords_align = "middle" # can be "top" , "middle" , or "bottom"
chords_parenthesis = True
